spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL:localhost}:5432/digitals
    username: ${DATASOURCE_USERNAME:digitals}
    password: ${DATASOURCE_PASSWORD:digitals}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect