server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: digital-signature-system

  profiles:
    include: ${SPRING_PROFILES_INCLUDE:datasource}

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

minio-config:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:digitals}
  secret-key: ${MINIO_SECRET_KEY:digitals}
  bucket: ${MINIO_BUCKET:documents}